### ISSUE TITLE
basic windows support

### ISSUE THREAD

**Issue by 0xxff** [0xxff/prompt-sync#4]

**Comment by yegodz** [comment]
hi... any idea how this could be done on windows?
/dev/stdin does not seem to work.

I tried /c/CON but that does not work either

**Comment by davidmarkclements** [comment]
maybe pipe `process.stdin` into a tmp file and openSync the tmp file?

**Comment by davidmarkclements** [comment]
got a solution: PR here: https://github.com/0xxff/prompt-sync/pull/9
